server:
  port: ${SERVER_PORT:8000}
spring:
  config:
    import: classpath:application-routes.yml
  application:
    name: api-gateway
  profiles:
    default: local
  threads:
    virtual:
      enabled: true
  main:
    keep-alive: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
platform:
  mvp:
    city: HAN
    vehicle-type: MOTORBIKE
    payment-method: INTERNAL_WALLET
    currency: VND
    timezone: Asia/Ho_Chi_Minh
